repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.275
    hooks:
      - id: ruff
        args: [ --fix ]
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
        additional_dependencies:
          - "sqlalchemy>=2.0.17,<3.0.0"
          - "pydantic>=1.8.1,<2.0.0"
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.48.0
    hooks:
      - id: eslint
        files: ^bin/egd_web/
        args: [ "--fix", "--config", "bin/egd_web/.eslintrc.json" ]
        types: [ file ]
        types_or: [ javascript, jsx, ts, tsx ]
        additional_dependencies:
          - "eslint@8.48.0"
          - "next@13.4.9"
